config/routes.rb
Rails.application.routes.draw do

  get 'comments/new'

  get 'comments/create'

  get 'comments/destroy'

  resources :users
  resources :ditties do
    resources :comments
  end

   resources :sessions, only: [:new, :create]
   delete '/logout', to: 'sessions#destroy'
  root 'users#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :ditty
end

app/models/ditty.rb
class Ditty < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :ditties
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    helper_method :current_user
  def current_user
    session[:user_id] ? User.find(session[:user_id]) : nil
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
    @comment = Comment.new
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
    @ditty = Ditty.find(params[:ditty_id])
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.body = comment_params[:body]
    # @comment.ditty = Ditty.find(params[:ditty])
    @comment.user_id = @user
    if @comment.save
      flash[:notice] = "Comment posted"
      redirect_to root_path
    else
      flash[:notice] = "Something went wrong"
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:user, :body, :ditty_id)
  end
end

app/controllers/ditties_controller.rb
class DittiesController < ApplicationController
    before_action :set_ditty, only: [:edit, :update, :destroy]
  def index
    @ditties = Ditty.all
  end

  def show
    @ditty = Ditty.find(params[:id])
    @comment = Comment.new
    # @comment = Comment.where(params[:id])
  end

  def new
    @ditty = Ditty.new
  end

  def create
    @ditty = Ditty.new(ditties_params)
    if @ditty.save
      flash[:notice] = "New ditty posted"
      redirect_to @ditties
    else
      flash[:notice] = "Something went wrong."
      render :new
    end
  end

  def edit
  end

  def update
    if @ditty.update(ditties_params)
      flash[:notice] = "Ditty updated"
      redirect_to @ditty
    else
      flash[:alert] = "Something went wrong"
      render :edit
    end
  end

  def destroy
    @ditty.destroy
    flash[:notice] = "Ditty deleted"
    redirect_to users_path
  end

  private

  def ditties_params
      params.require(:ditty).permit(:body, :player)
  end


  def set_ditty
    @ditty = Ditty.find(params[:id])
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.where(email: params[:email]).first
    if @user and @user.password == params[:password]
      session[:user_id] = @user.id
      flash[:notice] = "Logged in"
      redirect_to users_path
    else
      flash[:alert] = "There was a problem logging you in"
      redirect_to new_session_path
    end
  end

  def destroy
   # @session = User.find(current_user)
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :follow, :unfollow]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Sign up successful."
      redirect_to @user
    else
      flash[:notice] = "Something went wrong."
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Profile updated"
      redirect_to @user
    else
      flash[:alert] = "Something went wrong"
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:notice] = "Account deleted."
      redirect_to users_path
    else
      flash[:alert] = "Something went wrong"
      redirect_to users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:fname, :email, :password, :location, :lname, :username, :bio)
  end

  def set_user
      @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dittys_helper.rb
module DittysHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<h3>Comment</h3>

<%= form_for [ @ditty, @comment ] do |f| %>
  <p>
    <%= f.label :body, "Your Comment" %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
  <% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/index.html.erb
<ul>
  <% @comments.each do |comment| %>
  <%= comment.body %>
<%end %>
</ul>

app/views/comments/new.html.erb
<h1>Comment here</h1>
<%= render 'form' %>
<%= link_to "Home", users_path %>

app/views/comments/show.html.erb
<div class="linkInput" style="display:none;"><%= @ditty.player %></div>
<h2><%= @ditty.body %></h2>
<p>by <%# @ditty.user.username %></p>


<!-- <a id="submit" >click</a> -->
<!--
<div>
  <span id="message"></span>
</div> -->


<div class="players">
</div>

<h3>Discuss</h3>
<%= render partial: 'comments/form' %>

<ul>
  <% @comments.all.each do |comment| %>
  <%= comment.body %>
</ul>

app/views/ditties/_form.html.erb
<div id="inputs">

<%= form_for @ditty do |f| %>

  <%= f.text_area :player %>
  <%= f.text_area :body %>
  <%= f.submit %>

  <% end %>

	<div>
		<span id="message"></span>
	</div>
</div>

<div class="players">
</div>

app/views/ditties/create.html.erb
<h1>Dittys#create</h1>
<p>Find me in app/views/dittys/create.html.erb</p>

app/views/ditties/destroy.html.erb
<h1>Dittys#destroy</h1>
<p>Find me in app/views/dittys/destroy.html.erb</p>

app/views/ditties/edit.html.erb
<h1>Edit your ditty</h1>

<%= render 'form' %>

<%= link_to 'cancel', users_path %>

app/views/ditties/index.html.erb
<h1>Your Ditty feed</h1>

<br>
<br>
<ul>
  <% @ditties.all.each do |ditty| %>
  <div class="linkInput" >
<%= ditty.player %> 
  	</div>

<br>
  <div class="players"> 


  	<%= ditty.body %></div>
  
  <%end %>

</ul>

app/views/ditties/new.html.erb
<h1>Compose a Ditty</h1>
<%= render 'form' %>

<%= link_to 'cancel', users_path %>

app/views/ditties/show.html.erb
<div class="linkInput" style="display:none;"><%= @ditty.player %></div>
<h2><%= @ditty.body %></h2>
<p>by <%# @ditty.user.username %></p>


<!-- <a id="submit" >click</a> -->
<!--
<div>
	<span id="message"></span>
</div> -->


<div class="players">
</div>

<h3>Discuss</h3>
<%= render partial: 'comments/form' %>
<ul>
  <%= @comment.body %>
</ul>



<script>
$('a[href*="soundcloud.com"]').each(function(){
  var $link = $(this);
  $.getJSON('http://soundcloud.com/oembed?format=js&url=' + $link.attr('href') + '&iframe=true&callback=?', function(response){
    $link.replaceWith(response.html);
  });
});
</script>

<a href = "https://soundcloud.com/friendwithin/the-renegade">THIS SONG</a>

app/views/ditties/update.html.erb
<h1>Dittys#update</h1>
<p>Find me in app/views/dittys/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Socialmelody</title>

  <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <header>
    <nav>
      <% if current_user %>
        <%= "Hello #{current_user.username}" %> |
        <%= link_to "logout", logout_path, method: :delete %> |
        <%= link_to "Compose a Ditty!", new_ditty_path %>
      <% else %>
         <%= link_to "Sign up", new_user_path %> |
         <%= link_to "Sign in", new_session_path %>
      <% end %>
    </nav>
 </header>
<%= flash[:notice] if flash[:notice] %>
<%= flash[:alert] if flash[:alert] %>

<%= yield %>

	<script>
$(document).ready(function(){

$('#submit').ready(function(){
	if ($('.linkInput').html().indexOf('soundcloud.com') !== -1) {
		// $('#message').text('fetching player...');
		getPlayer($('.linkInput').html(), function(response) {
			$('.players').append(response.html);
			// $('#message').text('done');
		});
	} else {
		$('#message').text('Must input proper soundcloud link');
	}
});

var getPlayer = function(link, callback) {
	$.getJSON('http://soundcloud.com/oembed?format=js&url=' + link + '&iframe=true&callback=?', callback);
};
});
	</script>




</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
  <%= f.label :email %>
  <%= f.text_field :email %><br>
  <%= f.label :password %>
  <%= f.text_field :password %><br>
  <%= f.label :fname, 'First Name' %>
  <%= f.text_field :fname %><br>
  <%= f.label :lname, 'Last Name' %>
  <%= f.text_field :lname %><br>
  <%= f.label :location %>
  <%= f.text_field :location %><br>
  <%= f.label :bio %>
  <%= f.text_field :bio %>
  <%= f.submit %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit your profile below</h1>

<%= render 'form' %>

<p><%= link_to 'cancel', user_path(@user) %> |
  <%=link_to 'back to users', users_path %>
</p>

app/views/users/index.html.erb
<h1>Welcome to Ditty</h1>
<h3>Share what you're listening to with friends</h3>

<p><%= link_to 'Sign Up', new_user_path %></p>
<ul>
  <% @users.each do |user| %>
  <li><%= link_to user.username, user %> |
    <%= user.bio %> |
    <%= link_to 'delete', user, method: :delete, data: { confirm: "Are you sure?"} %>
</li>
  <% end %>
  </ul>

app/views/users/new.html.erb
<h1> Create a new account below! </h1>

<%= render 'form' %>

<p><%= link_to 'cancel', users_path %></p>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<h3><%= @user.fname %>  <%= @user.lname %></h3>

<h4><%= @user.email %></h4>
<p>Location: <%= @user.location %></p>
<p>Bio: <%=@user.bio %></p>
<h3><%= @user.fname %>'s ditties</h3>
<ul>
  <% @user.ditties.each do |ditty| %>
  <li><%= link_to ditty.player, ditty %></li>
  <li><%= link_to ditty.body, ditty %></li>
  <% end %>
</ul>
<hr>
<p>
  <%= link_to 'edit user', edit_user_path(@user) %> |
  <%=link_to 'back to users', users_path %>
</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>